---
title: "Lambda_ratio"
author: "Jasper Velthoen"
date: "2/28/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\section{The learning rate}

There are two learning rates in the gbex algorithm, one for $\sigma$, $\lambda_{\sigma}$, and one for $\gamma$, $\lambda{\gamma}$. As both parameters influence each other in the algorithm we want to choose learning rates for both paramters in the right proportion, which we define to be the learning rate ratio $\lambda_{ratio} = \frac{\lambda_{\gamma}}{\lambda_{\sigma}}$. This ratio can be scaled by the learning rate size $\lambda_{size}$ to obtain the learning rates for each parameter in the following way,
$$
\lambda_{sigma} = \lambda_{size} \; \;\mbox{and} \; \; \lambda_{gamma} = \frac{\lambda_{size}}{\lambda_{ratio}}.
$$

Note that this would only require us to tune $\lambda_{ratio}$ and choose $\lambda_{size}$ sufficiently low such that the algorithm is able to find a stable minimum. 

We consider the choice for 3 different simulation models, where we simualte $\mathbf{X} \in \mathbb{R}^{10}$ all independently uniform random variables on the interval $[-1,1]$. The models are then given by,
\begin{description}
\item[Model 1]$Y \sim GPD(\sigma = 1 + \frac{X_1}{2},\gamma = 0.4)$
\item[Model 2]$Y \sim GPD(\sigma = 1 + \frac{X_1}{2},\gamma = 0.4 + \frac{X_2}{10})$
\item[Model 3]$Y \sim GPD(\sigma = 1 + \frac{X_1}{2},\gamma = 0.4 + \frac{X_2}{5})$
\end{description}

The motivation for these models is to investigate how the ratio cha


By means of simulation we compare 3 different simulation models and test how the optimal $\lambda_{ratio}$ is chosen.
We consider the following 3 models
